services:
  open-webui:
    # Если меняете код локально — оставьте блок build.
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # # Или используйте только образ:
    # image: ghcr.io/open-webui/open-webui:main
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    env_file: .env
    container_name: open-webui
    ports:
      - "${OPEN_WEBUI_PORT-3000}:8080"
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  open-webui-data: {}